### PR TITLE
add spack config yaml and template to generate dockerfile

### PR DESCRIPTION
**Pull request by rem1776**
Updates to use a spack generated dockerfile. The dockerfile changes were generated with spack with the added yaml and template file. I included instructions for generating it in the yaml file.

As is it will download latest compatible versions for dependencies, but we can install any versions (or build options) available in spack via the config yaml.

### CODE REVIEW

**Comment by underwoo** [comment]
@rem1776 do I sill need to review this?

**Comment by rem1776** [comment]
@underwoo Yes this should still go in.

**Comment by rem1776** [comment]
@underwoo Actually on second thought, should we move the contents of this repository to hpc-me? Since it holds the FMS CI dockerfiles as well it'd probably be better to consolidate these files there.

**Comment by underwoo** [comment]
I'll merge this.  If you do decide to migrate the container to the other project, we should probably close this project.

**Pull request merged**
